<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>SeeMenuAndOrder</description>
   <name>SeeMenuAndOrder</name>
   <tag></tag>
   <elementGuidId>80853cf8-ce72-4f6e-a69d-e9881f427562</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='glfButton1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='glfButton1']</value>
   </webElementProperties>
</WebElementEntity>
