<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Jezik</description>
   <name>Sprachen</name>
   <tag></tag>
   <elementGuidId>1e373dc9-4ba9-46c9-9f7d-9d9cb9efd1f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[text()='Sprachen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[text()='Sprachen']</value>
   </webElementProperties>
</WebElementEntity>
