<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Close</description>
   <name>Close</name>
   <tag></tag>
   <elementGuidId>7f70db14-06a1-485a-9c2d-d86d536bb419</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='fb-close']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='fb-close']</value>
   </webElementProperties>
</WebElementEntity>
