<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Email</description>
   <name>Email-Input</name>
   <tag></tag>
   <elementGuidId>5c1755ef-a58b-4a04-a5cf-c1fab15398cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@class='js-contact-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@class='js-contact-email']</value>
   </webElementProperties>
</WebElementEntity>
