<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Name</description>
   <name>Name-Input</name>
   <tag></tag>
   <elementGuidId>59dd850c-9ef6-4ea7-9177-fe9bbf606063</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@class='js-contact-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@class='js-contact-name']</value>
   </webElementProperties>
</WebElementEntity>
