<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>RoboCheckBox</description>
   <name>Recaptcha-CheckBox</name>
   <tag></tag>
   <elementGuidId>a86d4c2d-3e5d-4d46-90f8-1ddb16673e7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='recaptcha-anchor']/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='recaptcha-anchor']/div[1]</value>
   </webElementProperties>
</WebElementEntity>
