<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>TextArea</description>
   <name>TextBox-Input</name>
   <tag></tag>
   <elementGuidId>e91f7cfc-5cc2-4a84-8fa9-d330dff2a949</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@class='js-contact-message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[@class='js-contact-message']</value>
   </webElementProperties>
</WebElementEntity>
