<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Email</description>
   <name>Email</name>
   <tag></tag>
   <elementGuidId>c0df1f91-a1b1-44ab-a031-5c62fdf3ef5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
   </webElementProperties>
</WebElementEntity>
