<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>LastName</description>
   <name>LastName</name>
   <tag></tag>
   <elementGuidId>0fea68c8-c557-4771-8590-bffd2e061ee4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='lastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='lastName']</value>
   </webElementProperties>
</WebElementEntity>
