<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>FirstName</description>
   <name>Name</name>
   <tag></tag>
   <elementGuidId>79eccd45-5e53-4629-931e-3a79dc8274d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='firstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='firstName']</value>
   </webElementProperties>
</WebElementEntity>
