<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Phone</description>
   <name>Phone</name>
   <tag></tag>
   <elementGuidId>2d827e39-4b31-4586-b94d-c22ba03fc927</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='phone']</value>
   </webElementProperties>
</WebElementEntity>
