<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Quantity</description>
   <name>Kolicina</name>
   <tag></tag>
   <elementGuidId>b73c260e-4fb8-488f-92ba-ee72e382589d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@class='btn-increase']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@class='btn-increase']</value>
   </webElementProperties>
</WebElementEntity>
