<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Bloody</description>
   <name>SlaboPecen</name>
   <tag></tag>
   <elementGuidId>1686a101-f111-4ce5-a677-5a306652fbd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ui-view[@id='fb-content']/app-restaurant/div/ui-view/app-menu/ui-view/app-addons/div[@class='fb-addons']//form[@name='addons']/div[@class='js-error-1410968']/div[@class='cb-wrapper']/div[1]/label/div[@class='options-label-table']/div[@class='options-label-row']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ui-view[@id='fb-content']/app-restaurant/div/ui-view/app-menu/ui-view/app-addons/div[@class='fb-addons']//form[@name='addons']/div[@class='js-error-1410968']/div[@class='cb-wrapper']/div[1]/label/div[@class='options-label-table']/div[@class='options-label-row']/div[2]</value>
   </webElementProperties>
</WebElementEntity>
